application:
  name: gateway-server

server:
  port: 8080

spring:
  config:
    import:
      - "nacos:gateway-server"
#      - "classpath:jwt_properties.yml"
#      - "classpath:user_message_properties.yml"
  cloud:
    nacos:
      config:
        server-addr: 106.53.106.123:8848
        file-extension: yaml
        refresh-enabled: true

