application:
  name: gateway-server

server:
  port: 8080

spring:
  config:
    import:
      - "nacos:gateway-server"
#      - "classpath:jwt_properties.yml"
#      - "classpath:user_message_properties.yml"
  cloud:
    loadbalancer:
      configurations: request-based-sticky-session
      sticky-session:
        add-service-instance-cookie: true
        instance-id-cookie-name: "sc-lb-itc-id"
    nacos:
      discovery:
        server-addr: localhost:8848
        register-enabled: false
        enabled: true
      config:
        server-addr: localhost:8848
        file-extension: yaml
        refresh-enabled: true

