application:
  name: gateway-server

server:
  port: 8080

spring:
  config:
    import: "nacos:gateway-server.yaml"
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user
          uri: lb://user-server
          predicates:
            - Path=/user/**,/api/user/**
        - id: user-api
          uri: lb://user-server
          predicates:
            - Path=/user/**
#        - id: oauth2-callback
#          uri: //localhost:8080
#          predicates:
#            - Path=/login/oauth2/code/**  # 确保路径透传到下游服务
#          filters:
#            - StripPrefix=0  # 禁止截断路径前缀
#        - id: login
#          uri: lb://authorization-server
#          predicates:
#            - Path=/loginPage/**
#            - Path=/login/**

  security:
    oauth2:
      client:
        registration:
          gatewayClient:
            client-id: "gatewayClient"
            client-secret: "000000"
            authorization-grant-type: "authorization_code"
            redirect-uri: "http://8.138.34.108:8080/login/oauth2/code/gatewayClient"
            scope:
              - "openid"
#              - "profile"
            provider: "authorizationServer"
        provider:
          authorizationServer:
            issuer-uri: "http://8.138.34.108:8081"
#      resourceserver:
#        jwt:
#          issuer-uri: http://127.0.0.1:8081
#
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    reactor.netty: DEBUG
