server:
  port: 8082
  address: 127.0.0.1

spring:

  application:
    name: user-server

  config:
    import:
#      - "classpath:jwt_properties.yml"
#      - "classpath:user_message_properties.yml"
      - "nacos:user-server.yaml"

  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
        server-addr: localhost:8848

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://8.138.34.108:8081

  datasource:
    url: "jdbc:mysql://localhost:3306/wuying?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: "root"
    password: "000000"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    port: 3306

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          issuer-uri: "http://127.0.0.1:8081"

logging:
  level:
    org:
      springframework:
        security: DEBUG