server:
  port: 8082
  address: 127.0.0.1

spring:

  application:
    name: userServer

  cloud:
    nacos:
      server-addr: localhost:8848

  config:
    import:
    - "classpath:jwt_properties.yml"
    - "classpath:user_message_properties.yml"
    - "optional:nacos:user.yaml"

  datasource:
    url: "jdbc:mysql://localhost:3306/wuying?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: "root"
    password: "000000"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    port: 3306

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "http://192.168.119.1:8081"

logging:
  level:
    org:
      springframework:
        security: DEBUG