server:
  port: 8081
  address: 127.0.0.1

spring:

  application:
    name: user-server

  config:
    import:
      - "nacos:user-server"
#      - "classpath:jwt_properties.yml"
#      - "classpath:user_message_properties.yml"

  cloud:
    nacos:
      discovery:
        server-addr: 106.53.106.123:8848
        ip: 8.138.34.108
      config:
        server-addr: 106.53.106.123:8848
        file-extension: yaml
        refresh-enabled: true

