server:
  port: 8101

spring:

  application:
    name: authorization-server

  config:
    import:
      - "nacos:authorization-server"
#      - "classpath:jwt_properties.yml"
#      - "classpath:user_message_properties.yml"

  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        server-addr: 106.53.106.123:8848
#        namespace: public
#        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true


