server:
  port: 8081
  address: 127.0.0.1

spring:

  application:
    name: authorization-server

  config:
    import:
    - "classpath:jwt_properties.yml"
    - "classpath:user_message_properties.yml"
    - "nacos:authorization-server.yaml"

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  security:
    oauth2:
      authorizationserver:
        client:
          #客户端名字
          gatewayClient:
            registration:
              client-id: "gatewayClient"
              client-secret: "$2a$10$nDUzPNsp3WUWmSC3Mao3Q.hde98tpdUqh7MXLznpzbpOl/rEiD5C6"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/gatewayClient"
#              post-logout-redirect-uris:
#                - "http://localhost:8080/home"
              scopes:
                - "openid"
#                - "profile"
##            require-authorization-consent: true

logging:
  level:
    org:
      springframework:
        authorizationServer: TRACE
        security: TRACE
        oauth2: TRACE