server:
  port: 8101

spring:
  application:
    name: authorization-server
  config:
    import:
      - "nacos:authorization-server"
#      - "classpath:jwt_properties.yml"
#      - "classpath:user_message_properties.yml"

  cloud:
    nacos:
#      discovery:
#        server-addr: localhost:8848
#        register-enabled: true
#        enabled: true
      config:
        server-addr: localhost:8848
#        namespace: public
#        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true


