server:
  port: 8101

spring:
  application:
    name: authorization-server
  config:
    import:
      - "nacos:authorization-server"
#      - "classpath:jwt_properties.yml"
#      - "classpath:user_message_properties.yml"

  cloud:
    nacos:
#      discovery:
#        server-addr: localhost:8848
#        register-enabled: false
#        enabled: false
      config:
        server-addr: localhost:8848
        file-extension: yaml
        refresh-enabled: true


#  cloud:
#    nacos:
#      discovery:
#        port: 8100
#        server-addr: localhost:8848

